# Generated by Django 5.0 on 2024-01-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('talla', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'prenda',
            },
        ),
    ]
